import "./globals.css";
import type { Metadata } from "next";
import { Expletus_Sans } from "next/font/google";

const inter = Expletus_Sans({
	subsets: ["latin"],
	variable: "--font-expletus",
});

export const metadata: Metadata = {
	title: "True Perspective",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	);
}
